### PR TITLE
Added the logo designs

### PR DESCRIPTION
**Pull request by rahmot**

### CODE REVIEW

**Review by bebatut — COMMENTED** [review]
Thanks for that.

Could move the images folder inside a folder `assets`? And can you remplace spaces in file names by `_`?

**Comment by rahmot** [comment]
@bebatut thanks for the feedback. I have moved the images folder to assets.

**Comment by bebatut** [comment]
Thanks for moving the folder. Can you rename the files to replace the spaces by `_`?

**Comment by bebatut** [comment]
Which tool did you use to create the logo? Do you have the raw version of it? Could you also create a `README.md` file in the folder and add in it information like the font, color, etc? Thanks a lot

**Comment by bebatut** [comment]
Done in #9

**Pull request closed without merging**
