### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by assuntad23**
This template will help us all be aware of what we are submitting as PRs and what we've done to ensure their success. It will make it much easier and faster to approve PRs too!

### CODE REVIEW

**Comment by assuntad23** [comment]
@bebatut Whenever you get a chance to take a look at this and merge it in, I think this will improve our pull request process greatly!

@Chinonyemildred  & @rahmot  Please take a look at this too! Feel free to add any comments or suggestions you think will help improve the process! 😄

**Comment by Chinonyemildred** [comment]
This guide will go a long way to helping us and future contributors in creating detailed PRs :)

**Comment by rahmot** [comment]
This is great @assuntad23. Thanks! :)

**Comment by bebatut** [comment]
It looks. I merge. Thanks @assuntad23

**Pull request merged**
