### PR TITLE
Moved footer to default.vue

### PR DESCRIPTION
**Pull request by Chinonyemildred**
I moved the footer to the default.vue file

### CODE REVIEW

**Comment by bebatut** [comment]
It looks a bit strange
image

Some suggestions:
- Not sure about putting the names of people directly. Why not forwarding directly to the public Matrix? 
- Maybe better "Get in touch" than "Help and Support"?
- We should also add the license

Maybe something like:

image

**Comment by Chinonyemildred** [comment]
> It looks a bit strange image
> 
> Some suggestions:
> 
> * Not sure about putting the names of people directly. Why not forwarding directly to the public Matrix?
> * Maybe better "Get in touch" than "Help and Support"?
> * We should also add the license
> 
> Maybe something like:
> 
> image

It does look strange...the hyperlinked words are supposed to be colored....when I used inline styling for the background color, it looked great. I'm not sure about it in a separate `style tag`.

I'll change the contents now. Please where do I get the license from? The hub repo right?

**Comment by Chinonyemildred** [comment]
> We define the license: I think we can use the same `CC BY SA 4.0`

Yeah, I looked it up online and added it to the commit. Thank you :)

**Comment by bebatut** [comment]
I will merge and fix all the style things in another PR. Thanks @Chinonyemildred

**Comment by Chinonyemildred** [comment]
This is a lot of improvement! Thank you so much!!

**Pull request merged**
